### ISSUE TITLE
Mobile Verifier - v1

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1168]
- [x] Wallet Name
- [ ] How/Where to access "My QR Code"
  - [ ] From Camera Screen?
  - [ ] From Settings* (Open Camera Screen with default "My QR Code")
- [ ] How/Where to request proof
  - [ ] From Contact
  - [ ] From Settings
