### ISSUE TITLE
Manual Testing for 1.0.10

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1279]

**Comment by jleach** [comment]
Manual Testings for iOS

- [x] Showcase as Student
- [ ] Showcase as Lawyer
- [ ] LSBC Test Environment
- [ ] LSBC Prod environment
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [ ] Mobile Verifier

**Comment by knguyenBC** [comment]
Testing with Build 1087

Manual Testings for iOS: iPhone SE

- [X] Showcase as Student (test): **FAILED** - Credential offer gets stuck after accepting the credential. #1303
- [X] Showcase as Student (prod): PASS
- [X] Showcase as Lawyer (test): **FAILED** - Credential offer gets stuck after accepting the credential. #1303
- [X] Showcase as lawyers (prod): PASS
- [X] Unverified Person: PASS
- [X] LSBC Test Environment: *see below
- [X] LSBC Prod environment: PASS* see below
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [X] Mobile Verifier: PASS**
- [X] Animo demo: PASS

Manual Testings for Android

- [X] Showcase as Student (test): **FAILED** - Credential offer gets stuck after accepting the credential. #1303
- [X] Showcase as Student (prod): **FAILED** - Information sent successfully but showcase does not register information #1304
- [X] Showcase as Lawyer (test): **FAILED** - Credential offer gets stuck after accepting the credential. #1303
- [X] Showcase as Lawyer (prod): **FAILED** - Unable to accept proof request. Error code 1027. #1305
- [x] Unverified Person: PASS
- [X] LSBC Test Environment: *see below
- [X] LSBC Prod environment: *see below
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [X] Mobile Verifier: PASS **
- [X] Animo demo: 


*LSBC issuance test environment: PASS. works as intended.
ACM verification test environment with test credentials: **FAIL**. Gets stuck in loading the proof request.
ACM verification prod environment with test credential: PASS. works as intended.

** Creating a connection does not automatically take the person to the Contact screen.

**Comment by nodlesh** [comment]
Testing with Build 1087

Manual Testings for iOS (iPhone 6S iOS 15.7.1)
- [x]  Showcase as Student
**Failed** - Scanning QR code at https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/demo stayed on the scan screen with no error
Second & third runs, went to the connection screen and just spun. 
- [ ]  Showcase as Lawyer
- [x]  Unverified Person
- [ ]  LSBC Test Environment
- [ ]  LSBC Prod environment
- [ ]  Accessibility: Voice Control, Labels
- [x]  Automated testings are passing
- [x]  Mobile Verifier


Manual Testings for Android (UMIDIGI A3S Android 10)
- [x]  Showcase as Student
**Failed** - After Scanning QR code, and accepting a cred offer, went to the credential is on the way screen and just stayed there. https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/demo  Going to the Contact screen shows I sent a credential request. Showcase still shows "Accept the request in your wallet.
- [ ]  Showcase as Lawyer
- [x]  Unverified Person
- [ ]  LSBC Test Environment
- [ ]  LSBC Prod environment
- [ ]  Accessibility: Voice Control, Labels
- [x]  Automated testings are passing
- [x]  Mobile Verifier
**Failed** - As Holder #1296

**Comment by knguyenBC** [comment]
Testing with Build 1089

Manual Testings for iOS

- [X]  Showcase as Student (test): PASS
- [X]  Showcase as Student (prod): PASS
- [X]  Showcase as Lawyer (test): PASS
- [X]  Showcase as lawyers (prod): PASS
- [X] Unverified Person: PASS
- [X] LSBC Test Environment:  **FAIL** #1309
- [ ] LSBC Prod environment
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [X] Mobile Verifier: **FAIL** - #1314. 


Manual Testings for Android

- [X]  Showcase as Student (test): PASS
- [X]  Showcase as Student (prod): PASS
- [x]  Showcase as Lawyer (test): PASS
- [X]  Showcase as lawyers (prod): PASS
- [X] Unverified Person: PASS
- [X] LSBC Test Environment: FAIL #1309
- [ ] LSBC Prod environment
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [X] Mobile Verifier: **FAIL** - #1314.

**Comment by jleach** [comment]
Testing with 1.0.10 Build 1094

Manual Testings for iOS

- [ ] Showcase as Student
- [ ] Showcase as Lawyer
- [ ] Unverified Person
- [x] LSBC Test Environment
- [ ] LSBC Prod environment (**no access**)
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [ ] Mobile Verifier

**Comment by knguyenBC** [comment]
Testing with Build 1094

Manual Testings for iOS

- [ ]  Showcase as Student (test): 
- [X]  Showcase as Student (prod): PASS 
- [X]  Showcase as Lawyer (test): 
- [X]  Showcase as lawyers (prod): PASS 
- [ ] Unverified Person: 
- [ ] LSBC Test Environment: 
- [X] LSBC Prod environment: PASS *Issues with keycloak unrelated to BC Wallet.
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [ ] Mobile Verifier: 


Manual Testings for Android

- [ ]  Showcase as Student (test): 
- [X]  Showcase as Student (prod): PASS
- [ ]  Showcase as Lawyer (test): 
- [X]  Showcase as lawyers (prod): PASS
- [ ] Unverified Person: 
- [ ] LSBC Test Environment: 
- [X] LSBC Prod environment: PASS
- [ ] Accessibility: Voice Control, Labels
- [ ] Automated testings are passing
- [ ] Mobile Verifier:

**Comment by jleach** [comment]
Testing with 1.0.10 Build 1097

Manual Testings for iOS

- [x] Showcase as Student
- [x] Showcase as Lawyer
- [x] Unverified Person
- [x] LSBC Test Environment (very, very slow)
- [x] LSBC Prod environment (**no access**) (See Kim's comment below)
- [x] Accessibility: Voice Control, Labels
- [x] Automated testings are passing (See Shel's comment below)
- [x] Mobile Verifier

NOTES
- During accessibility testing I noted one existing issue and created #1322;
- During verifier testing noted text alignment issues, created #1323 to track;
- Small button alignment issue reported in #1324;
- The Terms and Conditions screen cannot be scrolled by voice control #1325;
- An accessibility label is shown on the chat bubble where it should not be #1326;
- Shell reported no noteworthy issues in iOS automated **smoke** tests run.

**Comment by bryce-mcmath** [comment]
Testing with 1.0.10 Build 1097

Manual Testings for Android

- [x] Showcase as Student
- [x] Showcase as Lawyer
- [x] Unverified Person
- [x] LSBC Test Environment (slow)
- [x] LSBC Prod environment (**no access**)
- [x] Accessibility (definitely not as pleasant on Android with TalkBack as it is with iOS and Voiceover but that wasn't due to any fault of the wallet)
- [x] Automated testings are passing (TBA)
- [x] Mobile Verifier

NOTES
- LSBC Test only worked with the unverified person credential from this link: https://openvp-rev-issuer-test.apps.silver.devops.gov.bc.ca/issue-credential, not from the candy one here: https://openvp-candy-issuer-test.apps.silver.devops.gov.bc.ca/issue-credential (it said didn't satisfy proof, I think this is intentional)
- LSBC Test was slow to issue credential and send information (maybe 30-45 seconds?)

**Comment by knguyenBC** [comment]
Testing with 1.0.10 build 1097

Manual testing for iOS
- [X] LSBC Prod environment: PASS

Testing with 1.0.10 build 1094

Manual testing for Android
- [X] LSBC Prod environment: PASS

**Comment by nodlesh** [comment]
Testing with Build 1097

Manual Testings for iOS
- [x]  Showcase as Student
- [x]  Showcase as Lawyer
- [x]  Unverified Person
- [ ]  LSBC Test Environment
- [ ]  LSBC Prod environment
- [ ]  Accessibility: Voice Control, Labels
- [x]  Automated testings are passing
- [x]  Mobile Verifier


Manual Testings for Android
- [x]  Showcase as Student
- [x]  Showcase as Lawyer
- [x]  Unverified Person
- [ ]  LSBC Test Environment
- [ ]  LSBC Prod environment
- [ ]  Accessibility: Voice Control, Labels
- [x]  Automated testings are passing
- [x]  Mobile Verifier

There is only one concern I have and that is for the last few days I'm seeing a problem in initializing. We haven't had that for a while now, but it happened two times last night, and once in the previous nights run.
I don't think this should hold up the release. I'm currently putting in a handler for this in the tests to do a soft assert and then retry the initialization. Right now it fails the test if this happens once.

The only other issue is sometimes scanning the QR Code on Android just shows the scan window and does nothing. No invalid code message, just like the QR code is not there. I'm also putting in some handling around this to see if I can determine what is going on. This may be a test infrastructure issue rather than an app issue.

**Comment by bryce-mcmath** [comment]
One thing to note, I was having issues getting the production person credential, mainly this error:![idim_error.PNG](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/b789c2f3-6423-429e-909f-d5d669657362)

**Comment by jleach** [comment]
I've created a release for iOS and Android but we need new iPad screen shots for iOS so I have not submitted them for review.
