### ISSUE TITLE
Release Readiness Checklist (1.0.11)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1399]
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [ ]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages

### What is new?
```text
- Improvements to the notifications display
- Notification for basic messages
- Warning if sharing information flagged as sensitive by the issuer
- Miscellaneous bug fixes and improvements
```

**Comment by bryce-mcmath** [comment]
My findings:
Showcase credentials are often never added to the wallet. Even when choosing 'send another credential' or restarting the app, no luck. Not all special characters in wallet names are preserved, ticket created here: https://app.zenhub.com/workspaces/bc-wallet-6148e7423fe04b001444e2bd/issues/gh/bcgov/bc-wallet-mobile/1429

Oftentimes once the first of the two showcase proof request demos are done, the second will be marked already completed and shortcut to the end of the demo.

Android had to be much closer to the QR code to scan properly compared to iOS.

**Comment by knguyenBC** [comment]
Build: 1182

**iOS**
- [x] Manual testings 
    - [X] Showcase (Student/Lawyer) - **FAIL.** student and lawyer showcase not issuing student card #212
    - [X]  LSBC Test Environment - **PASS-ish***. Tested with revocable unverified person + test lsbc credential. Took ~1min to load proof request. *Took a couple of minutes to send the information over (was stuck at loading screen for quite some time. Most people would give up after 1 minute)
    - [x]  LSBC Prod environment - PASS. sending information over took a minute.
    - [X]  Person credential: PASS
    - [X]  Accessibility: Voice Control, Labels: PASS
- [X] Mobile Verifier with Default and Dev Mode settings: **FAIL.** Revoked state not reflected in information received screen. #1437
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias):  PASS

**Android**
- [x] Manual testings 
    - [X] Showcase (Student/Lawyer): **FAIL**. Received credential offer but stuck at loading screen after accepting it. #212
    - [X]  LSBC Test Environment: PASS. getting test credentials and sending information over took 1-3 minutes. 
    - [X]  LSBC Prod environment: PASS. Sending information over took a minute
    - [X]  Person credential: PASS
    - [x]  Accessibility: Voice Control, Labels PASS. A few minor accessibility bugs but nothing blocking
- [X] Mobile Verifier with Default and Dev Mode settings: **FAIL.** Revoked state not reflected in information received screen. #1437 #1439
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias): **FAIL** - Characters in wallet name aren't displayed correctly. #1429

**Comment by knguyenBC** [comment]
Build: 1203

**iOS**
- [ ] Manual Testing
    - [X] Showcase (Student/Lawyer): PASS
    - [X] Single Device experience using showcase: **FAIL**. The showcase did not work using deep link #219 
    - [X]  LSBC Test Environment: **PASS-ish**. proof request load time and information sending takes a long time (about 1 min). 
    - [X]  LSBC Prod environment: **PASS-ish**. proof request load time and information sending takes a long time (about 1 min). 
    - [X]  Person credential: PASS
    - [ ]  Accessibility: Voice Control, Labels: 
- [X] Mobile Verifier with Default and Dev Mode settings: PASS
- [X] Connected experience (e.g.: messaging, proof request, wallet name/alias): **FAIL**. Credentials still allow people to share their revoked credentials #1439. revoked state not shown in proof request #1485.

**Android**
- [ ] Manual Testing 
    - [X] Showcase (Student/Lawyer): PASS
    - [X] Single Device experience using showcase: FAIL. The showcase did not work using deep link #219 
    - [X]  LSBC Test Environment: **PASS-ish**. proof request load time and information sending takes a long time (about 1 min). 
    - [X]  LSBC Prod environment: **PASS-ish**. proof request load time and information sending takes a long time (about 1 min). 
    - [X]  Person credential: **FAIL**. Getting an error message on the BCSC app. IDIM notified.
    - [ ]  Accessibility: Voice Control, Labels:
- [X] Mobile Verifier with Default and Dev Mode settings: PASS
- [X] Connected experience (e.g.: messaging, proof request, wallet name/alias): **FAIL**. Credentials still allow people to share their revoked credentials #1439. revoked state not shown in proof request #1485.

**Comment by jleach** [comment]
Latest build 1.0.11 Build 1246 has the deep link fix. I think it should be the one tested for the release.

**Comment by jleach** [comment]
1.0.11 Build 1246 - WORK IN PROGRESS

- [ ]  Manual testings
   - [x]  Showcase (Student/Lawyer)
   - [x]  LSBC Test Environment
   - [ ]  LSBC Prod environment ( NO ACCESS )
   - [ ]  Accessibility: Voice Control, Labels
   - [x]  Get Person Credential with BCSC App
- [x]  Automated testings are passing (Smoke test for iOS and Android OK)
- [ ]  Mobile Verifier with Default and Dev Mode settings
- [ ]  Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ]  Single Device experience using showcase
- [ ]  Use names/values supporting Indigenous Languages

**Comment by knguyenBC** [comment]
Build: 1246

**iOS**
- [ ] Manual Testing
    - [X] Showcase (Student/Lawyer): PASS. A little slow to receive credential 
    - [X] Single Device experience using showcase: PASS
    - [X]  LSBC Test Environment: **PASS**. Took a long time (a few minutes) to send information in a proof request.
    - [X]  LSBC Prod environment: PASS. A little slow getting a credential and acknowledgment that information was sent successfully but worked
    - [X]  Person credential: PASS
    - [ ]  Accessibility: Voice Control, Labels: 
- [x] Mobile Verifier with Default and Dev Mode settings: **FAIL** Connection/Contact is saved despite having data retention toggle off - #1529
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias): PASS

**Android**
- [ ] Manual Testing 
    - [X] Showcase (Student/Lawyer): PASS. A little slow to receive credential 
    - [X] Single Device experience using showcase: PASS
    - [X]  LSBC Test Environment: PASS. A little slow getting acknowledgment that information was sent successfully but worked
    - [X]  LSBC Prod environment: PASS. A little slow getting acknowledgment that information was sent successfully but worked
    - [X]  Person credential: PASS
    - [ ]  Accessibility: Voice Control, Labels:
- [x] Mobile Verifier with Default and Dev Mode settings: **FAIL** Connection/Contact is saved despite having data retention toggle off - #1529
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias): PASS

**Comment by bryce-mcmath** [comment]
**iOS**
- [ ] Manual Testing
    - [X] Showcase (Student/Lawyer): PASS. A little slow sometimes.
    - [X] Single Device experience using showcase: PASS
    - [X]  LSBC Test Environment: PASS
    - [ ]  LSBC Prod environment: No access
    - [X]  Person credential: PASS (sometimes there's a null value on the BCSC side but that doesn't seem to affect the flow
    - [ ]  Accessibility: Voice Control, Labels: 
- [ ] Mobile Verifier with Default and Dev Mode settings: the issue Kim described above exists
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias): PASS

**Android**
- [ ] Manual Testing 
    - [X] Showcase (Student/Lawyer): PASS. Sometimes slow
    - [X] Single Device experience using showcase: PASS
    - [X]  LSBC Test Environment: PASS
    - [ ]  LSBC Prod environment: No access
    - [X]  Person credential: PASS
    - [ ]  Accessibility: Voice Control, Labels:
- [ ] Mobile Verifier with Default and Dev Mode settings: same as above
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias): PASS

**Comment by nodlesh** [comment]
Build 1246
iOS & Android

- [ ]  Manual testings
   - [x]  Showcase (Student/Lawyer)
   - [ ]  LSBC Test Environment
   - [ ]  LSBC Prod environment
   - [ ]  Accessibility: Voice Control, Labels
   - [ ]  Get Person Credential with BCSC App
- [x]  Automated testings are passing
- [x]  Mobile Verifier with Default and Dev Mode settings
- [x]  Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x]  Single Device experience using showcase (deep linking)
- [x]  Use names/values supporting Indigenous Languages

**Comment by jleach** [comment]
Build 1252

## iOS

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment (**no credentials to test**)
    - [x]  Accessibility: Voice Control, Labels (**3**)
    - [x]  Get Person Credential with BCSC App
- [x] Automated testings are passing (**smoke tests on build - ok**)
- [x] Mobile Verifier with Default and Dev Mode settings (Full Name and Full Name + Age > 19)
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (**1**)
- [x] Use names/values supporting Indigenous Languages (**2**)

1. Deep Link from BCSC to Wallet Ok.
2. UTF-8 Ok
3. Accessibility label issues: #1536, #1537, #1538 , #1539, #1540, #1541, #1542.

**Comment by bryce-mcmath** [comment]
Build 1252

## Android

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer) - PASS
    - [x]  LSBC Test Environment - PASS
    - [ ]  LSBC Prod environment - no access
    - [ ]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App - PASS
- [x] Automated testings are passing - PASS (last I heard)
- [x] Mobile Verifier with Default and Dev Mode settings - PASS
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias) - PASS
- [x] Single Device experience using showcase - PASS
- [x] Special characters in names / values - PASS (special characters in wallet names work, although I wasn't able to test credential values)

**Comment by jeffaudette** [comment]
waiting for #1529

**Comment by nodlesh** [comment]
Build 1252
iOS & Android

 Manual testings
- [x]  Showcase (Student/Lawyer)
- [ ]  LSBC Test Environment
- [ ]  LSBC Prod environment
- [ ]  Accessibility: Voice Control, Labels
- [ ]  Get Person Credential with BCSC App
- [x]  Automated testings are passing
- [x]  Mobile Verifier with Default and Dev Mode settings
- [x]  Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ]  Single Device experience using showcase (deep linking)
- [x]  Use names/values supporting Indigenous Languages
