### ISSUE TITLE
Release Readiness Checklist (1.0.12)

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1617]
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [ ]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages

Change notes:
```text
- 
```

**Comment by jleach** [comment]
Testing iOS 1.0.12 1363

This release LGTM. Works well, received all credentials and proofs. Was fast. Logged two small accessibility label issues that pre-exist. Ship 🚢 it.

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test Environment
    - [ ] LSBC Prod environment (no access)
    - [x] Accessibility: Voice Control, Labels (2 small issues that exist in v1.0.11, #1638 and #1639)
    - [x] Get Person Credential with BCSC App
- [x] Automated testings are passing (confirmed by shell)
- [ ] Mobile Verifier with Default and Dev Mode settings (no 2nd phone)
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages

**Comment by knguyenBC** [comment]
testing Android version 1.0.12 Build 1365

- [x] Manual testings 
    - [X] Showcase (Student/Lawyer) - PASS
    - [x]  LSBC Test Environment - PASS
    - [X]  LSBC Prod environment - PASS
    - [ ]  Accessibility: Voice Control, Labels
    - [X]  Get Person Credential with BCSC App - PASS
- [X] Mobile Verifier with Default and Dev Mode settings - PASS
- [X] Connected experience (e.g.: messaging, proof request, wallet name/alias) - PASS
- [X] Single Device experience using showcase (deep linking) - PASS
- [X] Use names/values supporting Indigenous Languages - PASS

testing iOS version 1.0.12 Build 1365

- [x] Manual testings 
    - [X] Showcase (Student/Lawyer) - PASS
    - [X]  LSBC Test Environment - PASS-ish. Sometimes loading the proof request takes a LONG time, sometimes it's quick. I try gain until it works. 
    - [X]  LSBC Prod environment - PASS
    - [ ]  Accessibility: Voice Control, Labels
    - [X]  Get Person Credential with BCSC App - PASS. A little slow though compared to Android. 
- [X] Mobile Verifier with Default and Dev Mode settings- PASS. A little slow retrieving the proof request and retrieving the list of multiple credentials that can satisfy the proof request.
- [X] Connected experience (e.g.: messaging, proof request, wallet name/alias) - PASS
- [X] Single Device experience using showcase (deep linking) - PASS
- [X] Use names/values supporting Indigenous Languages - PASS

Other notes: 

- Noticed that there's only ONE production lawyer credential in my wallet but when used in a proof request, it says I have two. Not sure how.
