### ISSUE TITLE
Release checklist 1.0.17

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#1965]
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.16 -> 1.0.17
- [x] Update ledger nodes via script

### Change notes:
```text
TBD
```

### Defects
- #1963 
- #1966
- #1954
- #1968
- #1969
- #1971
- #1972
- #1973
- #1956

**Comment by jleach** [comment]
1.0.17 Build 1726

- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x]  LSBC Test Environment
    - [ ]  LSBC Prod environment
    - [ ]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.16 -> 1.0.17


## Notes
- LSBC, getting a credential Ok. Unable to test proof for ACM without the Person credential (decommissioned). 
- No proofs available to me under that I have credentials for as a mobile verifier

**Comment by jleach** [comment]
@cvarjao My testing on 1.0.17 seems fine. It works in all that I can test with the exception of Voice Control accessibility on iOS and Android. For iOS mine just stoped responding to "tap" commands and for Android the labels are mostly borked.


**iOS 1.0.17 Build 1740**

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
    - [x] Get an Attestation Credential.
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.16 -> 1.0.17


**Android 1.0.17 Build 1740**

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
    - [x] Get an Attestation Credential.
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.16 -> 1.0.17


## Notes
- No access it LSBC prod for testing.
- Android Person Credential was Test env only.
- Test Layer and Photo / 19+ Photo templates (no creds to test others).
- Voice Access on Android is unusable.
- Voice Control on iOS is broken on my device.

**Comment by knguyenBC** [comment]
**Android 1.0.17 build 1740 (Pixel 8)**
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [x]  LSBC Prod environment: **FAIL** asked for app attestation when scanning the QR code to access ACM. 
    - [ ]  Accessibility: Voice Control, Labels
    - [x]  Get Person Credential with BCSC App: **FAIL** Get a deep link error message. #2007 and a
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings. **Pass?** Still have issues with mobile verifier between two phones, even after upgrade from 1.0.16 to 1.0.17. When receiving a proof request from an iOS device that upgraded to 1.0.17 from 1.0.16, accepting a proof request will display a success but the iOS will show that it was rejected. However, after reissuing credentials, that seemed to have helped.
- [X] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.16 -> 1.0.17
- [ ] Update ledger nodes via script

**iOS 1.0.17 build 1740 (iPhone SE and upgraded from 1.0.16)**
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ]  LSBC Test Environment
    - [x]  LSBC Prod environment
    - [x]  Accessibility: Voice Control, Labels: **FAIL**: Accessibility labels in Contact lists all are labelled "A Contact" #2008 and similarly #2009 
    - [x]  Get Person Credential with BCSC App: Couldn't get Person credential as problem with BCSC app (error 204)
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings. **Pass?** . Still have issues with mobile verifier between two phones, even after upgrade from 1.0.16 to 1.0.17. When receiving a proof request from an Android device, an error 1043 unable to retrieve credentials for proof appears after trying to share information. However after trying a second time, it seemed to have worked.
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking) FAIL - Tried with showcase, received deeplinking error.
- [ ] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.16 -> 1.0.17
- [ ] Update ledger nodes via script

### Notes
Overall, a few random bugs for both devices on v 1.0.17 build 1740. Some issues happened only once where when I tried again after closing and opening the app, reissuing credentials, or restarting the process,  it seemed to consistently work afterwards. 
For example, I somehow got an error when getting my Person credential that said I wasn't using an accepted digital wallet. However, everything worked fine after exiting out of the issuance process and trying again.

**Comment by jleach** [comment]
**iOS 1.0.17 Build 1744**

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [ ] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
    - [x] Get an Attestation Credential.
- [x] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.16 -> 1.0.17


**Android 1.0.17 Build 1744**

- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
    - [x] Get an Attestation Credential.
- [x] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.16 -> 1.0.17


## Notes
- 1.0.16 too a little while to initialize on first install.
- Person tested with SIT environment.
- Used "Practicing lawyer" proof ran into issue #1972, otherwise good.
- Found a few small iOS accessibility issues. #2015 and #2016.
- I don't fine Android Voice Access overly usable #2017.
- When sharing 1.0.16 (verifier) -> 1.0.17 (holder) the 1.0.16 version did not update indicating it received any information. It did vibrate to indicate it received the connection.  1.0.17 -> 1.0.17 worked as expected. Marking test as Ok.
