### ISSUE TITLE
Release Checklist: 1.0.18

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2060]
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [ ] Get Person Credential with BCSC App
        - [ ] Check issuance of Attestation Credential
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.17 -> 1.0.18

**Comment by knguyenBC** [comment]
**Android Pixel 8 build 1792**
- [ ] Manual testings 
    - [X] Showcase (Student/Lawyer)- **FAIL**. App crashes when scanning credential issuance QR code #2065 . 
    - [X] LSBC Test environment
    - [x] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App - **FAIL**. Did not revoke the older Person credential immediately #2064. Ghost push notification when starting Person credential issuance #2062 
        - [x] Check issuance of Attestation Credential. Note: Attestation credential proof request is visible in the Service BC Chat.  This may cause alarm as people do not know what this is. #2063 
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking). Showcase is fine, but ACM or Courthouse libraries does not work.
- [ ] Use names/values supporting Indigenous Languages
- [X] Upgrade from 1.0.17 -> 1.0.18

**iOS iPhone SE**
- [ ] Manual testings 
    - [X] Showcase (Student/Lawyer)- **FAIL**. App crashes when scanning proof request QR code (after revoking lawyer credential) #2065
    - [x] LSBC Test environment
    - [x] LSBC Prod environment 
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App - **FAIL**. Did not revoke the older Person credential immediately #2064. 
        - [ ] Check issuance of Attestation Credential
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking). Showcase is fine, but ACM or Courthouse libraries does not work.
- [ ] Use names/values supporting Indigenous Languages
- [X] Upgrade from 1.0.17 -> 1.0.18

Note: Revocation doesn't seem to be working. HUGE delays for both the Person credential and LSBC credential. #2064

**Comment by jleach** [comment]
iPhone 14 Pro

- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [x] App running in background (before logout)
    - [ ] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.17 -> 1.0.18
