### ISSUE TITLE
Release Checklist - 1.0.19

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#2123]
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [ ] Get Person Credential with BCSC App
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.18 -> 1.0.19

**Comment by jleach** [comment]
**Android** v1.0.19 Build 1877

- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [x] Check when Schema and CredDef  are from different DIDs
- [x] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground
    - [x] App running in background (before logout)
    - [x] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.18 -> 1.0.19


Notes:
- Accessibility: Voice Control, Labels - no worse than 1.0.18 on Android;
- LSBC test account not working so I can not test this.
- Automated tests reported as passing on backlog call this morning so I marked it as such.
- Update Ok. Credentials preserved and usable.

**Comment by knguyenBC** [comment]
### Android
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [x] LSBC Prod environment. PASS. however
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App. FAIL. Credentials are not displayed as revoked. When a credential that should have been reokved is used in a proof, the proof is successfully sent but the verifier receives a declined/rejected response.
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground
    - [x] App running in background (before logout)
    - [x] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.18 -> 1.0.19

### iOS
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer). FAIL. not connecting with either student or lawyer showcase.
    - [x] LSBC Test environment. FAIL not sending credential offer
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [ ] Get Person Credential with BCSC App
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.18 -> 1.0.19

**Comment by knguyenBC** [comment]
### Android build 1890
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [x] LSBC Prod environment. 
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App. 
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [x] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.18 -> 1.0.19

### iOS build 1890
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [x] LSBC Prod environment. PASS. However, a revoked credential is being automatically selected first. I have to change the credential to a non-revoked one manually.
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App. 
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking): receiving and successfully sending the information, but returning to the service page (Courthouse libraries), VC-AuthN did not redirect me, Stuck in perpetual loading.
    - [x] App not running at all in background/foreground. FAIL
    - [x] App running in background (before logout). FAIL
    - [x] App running in background (after logout). FAIL
- [x] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.18 -> 1.0.19
