### ISSUE TITLE
Release Checklist - 1.0.21

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#2263]
- [ ] Manual testings 
    - [ ] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [ ] Get Person Credential with BCSC App
        - [ ] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [ ] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.20 -> 1.0.21

### What's New?
```
```

**Comment by al-rosenthal** [comment]
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [x] Check when Schema and CredDef  are from different DIDs
- [x] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [x] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground
    - [x] App running in background (before logout)
    - [x] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.20 -> 1.0.21

Notes:
- `View Offer` When clicking View offer from Contacts -> Contact the app displays an error: 1033 - Credential not found even though credential is in my wallet. The app then navigates to an empty credential details screen (testing with Showcase credentials)
- Removing a contact from contact list does not automatically refresh the list, so the old contact can still be interacted with (leads to an empty chat screen)
- Voice access cannot open a credential on the credential list page (android)
- Auto lock time settings have extra voice access labels
- Deep linking not working when app is in background still logged in [2252](https://github.com/bcgov/bc-wallet-mobile/issues/2252)
- Deep linking not working when app is in background not logged in [2252](https://github.com/bcgov/bc-wallet-mobile/issues/2252)

**Comment by jleach** [comment]
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [ ] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [x] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.20 -> 1.0.21

## Notes
- Will complete single device once new deep link fixes are in (2252).

**Comment by tom11-nguyen** [comment]
- [x] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [ ] LSBC Test environment
    - [ ] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [x] Automated testings are passing
- [ ] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias)
- [ ] Single Device experience using showcase (deep linking)
    - [ ] App not running at all in background/foreground
    - [ ] App running in background (before logout)
    - [ ] App running in background (after logout)
- [ ] Use names/values supporting Indigenous Languages
- [ ] Upgrade from 1.0.20 -> 1.0.21

**Comment by knguyenBC** [comment]
### Android (build 
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [x] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias). 
- [ ] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground. **FAILED**. Fails when information is sent successfully, but returning to service page (ACM), vc-authn still says "accept the request in your wallet" then "this is taking longer than usual" for a long time (over a minute)
    - [x] App running in background (before logout)
    - [ ] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.20 -> 1.0.21

### iOS
- [ ] Manual testings 
    - [x] Showcase (Student/Lawyer)
    - [x] LSBC Test environment
    - [x] LSBC Prod environment
    - [x] Accessibility: Voice Control, Labels
    - [x] Get Person Credential with BCSC App
        - [x] Check issuance of Attestation Credential
    - [ ] Check when Schema and CredDef  are from different DIDs
- [ ] Automated testings are passing
- [x] Mobile Verifier with Default and Dev Mode settings
- [x] Connected experience (e.g.: messaging, proof request, wallet name/alias). 
- [ ] Single Device experience using showcase (deep linking)
    - [x] App not running at all in background/foreground. **FAILED**. Student showcase after information is sent successfully and returning to the showcase, there were no changes to the showcase.
    - [x] App running in background (before logout). **FAILED**. Student showcase, after information is sent successfully and returning to the showcase, there were no changes to the showcase.
    - [ ] App running in background (after logout)
- [x] Use names/values supporting Indigenous Languages
- [x] Upgrade from 1.0.20 -> 1.0.21

Other bugs
- #2293 
- #2295 
- #2294

Accessibility bugs
- #1451
- #2008 
- #2297
- #2296
- #2298
