### ISSUE TITLE
Add biometrics to onboarding process

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/bc-wallet-mobile#421]
As a user, I want to be able to choose to turn on biometrics so that I can choose the level of security for myself

### Acceptance Criteria

**Scenario 1: Holder has successfully created their PIN during onboarding**
Given the holder has successfully created their PIN during onboarding
When the Holder selects "Create PIN"
Then the Holder is taken to the [Biometrics page](https://xd.adobe.com/view/35c82052-5c29-4343-bab0-7dc84cebb129-609b/screen/a584635a-e2a6-4126-bbd9-baf33e6d438e)
And the option "use device biometrics" is default selected
  
**Scenario 2: Holder has chooses to use biometrics**
Given the Holder has selected to use biometrics to unlock BC Wallet
When the Holder opens the app
Then they are prompted to use their highest secure biometrics settings from their device (face unlock > fingerprint unlock)

**Scenario 3: Holder has chooses to not use biometrics**
Given the Holder has selected to use Wallet PIN only to unlock BC Wallet
When the Holder opens the app
Then they are prompted to input their wallet PIN

**Scenario 4: Holder does not have biometrics setup in their wallet**
Given the Holder does not have biometrics setup in their wallet
When the Holder selects to use biometrics to unlock BC Wallet
Then[ a notification](https://xd.adobe.com/view/f239cc67-e22a-4178-84ae-4cf06b1dff23-a76a/screen/ecde0712-a6db-473f-b05e-f0b6f0f5a785) pops up stating that they do not have biometrics unlock and to add it in phone settings

### TODO

- [x] 1. Holder has successfully created their PIN during onboarding
- [x] 2. Holder has chooses to use biometrics
- [x] 3. Holder has chooses to not use biometrics
- [ ] 4. Holder does not have biometrics setup in their wallet

**Comment by jleach** [comment]
@alexgmetcalf Do we consider biometrics and device PIN to be equal? Not to be confused with the application PIN.

**Comment by alexgmetcalf** [comment]
> @alexgmetcalf Do we consider biometrics and device PIN to be equal? Not to be confused with the application PIN.

@jleach Not sure if I understand the question properly; let’s chat?

**Comment by jleach** [comment]
Created #482 as a potential enhancement.

**Comment by jleach** [comment]
Scenario 4, this feature is not implemented. The library we use doe not have the ability to deterring what biometry is setup, only what is available. I've created issue #486 to track the implementation of this scenario when deemed important.

**Comment by nodlesh** [comment]
In the first scenario it states, `And the option "use device biometrics" is default selected`.
This is currently not the case. Was this a decision outside of this ticket or is this a bug?

**Comment by nodlesh** [comment]
Tests for this are defined here, https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/security.feature

Results of tests can be tracked here for iOS, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/ios-multi-device-full

and here for Android, https://allure-mobile.vonx.io/allure-docker-service-ui/projects/android-multi-device-full
