### ISSUE TITLE
App Unlocking Experience

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#870]
As a user
I want to be able to quickly unlock the app
so that I can use the app as quickly as possible

Main Goal: Speed

### Acceptance Criteria
- App is unlock and usable within 3s after entering PIN or validating biometrics
    -  Start and browse the app (see home screen)
    - Tapping a deep link to receive or present a credential (see connecting screen)

Notes:
- [ ] Define minimum devices (Android/iOS) and network requirements  (e.g.: 3G, LTE, WiFI)
- [ ] Blocked by transition from indy sdk  to vdr/shared-objects
- [ ] Blocked by adoption of [indy method](https://github.com/hyperledger/indy-did-method)

**Comment by nodlesh** [comment]
@cvarjao Was this epic supposed to be pushed to Review/QA? The issues under it are still in New state.

**Comment by cvarjao** [comment]
moved back to Needs Refinement

**Comment by cvarjao** [comment]
We have seen improvements since migrating to AFJ 0.4.0 (removed indy SDK)
