### ISSUE TITLE
QR Code Scanning User Experience

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#989]
- [ ] In-app camera scanning - /bcgov/bc-wallet-mobile/issues/1810
- [x] 3rd party Camera app(s) - bcgov/vc-authn-oidc/pull/273
- [x] OS/Device Camera scanning - bcgov/vc-authn-oidc/pull/273
- [x] Deep-link experience (makes it pop) - bcgov/vc-authn-oidc/issues/413
- [ ]  Security/Phishing aspect 
- [ ]  Single vs Multi device experience - bcgov/bc-wallet-mobile/issues/1811
   - how to return to the originating process/app? - https://github.com/hyperledger/aries-rfcs/issues/787
- [ ]  Micro-transaction / multi-step flow - /hyperledger/aries-mobile-agent-react-native/issues/803
- [x]  Issuer/Verifier QR Code page instructions [Delivery team] and related to bcgov/vc-authn-oidc#234
- [ ]  QR Code Branding - https://ditp-bc.atlassian.net/browse/DITDELIVER-781

### Acceptance Criteria
- Some research on how people use QR Code
- Provide 1 or more concept(s) for the user experience flow

**Comment by esune** [comment]
We're implementing the ability for `vc-authn` to detect when a non-wallet scanned the QR code, and redirect the webpage to something informative" (see https://github.com/bcgov/vc-authn-oidc/pull/273).

We are currently using https://id.gov.bc.ca/static/selfsetup.html as target page, but this is specific to the BCSC app. Is there a page that can be used for BC Wallet? If not, could one be created OR the BCSC page be updated to also describe onboarding for BC Wallet users? We might include a barebones, generic page with `vc-authn` however given the target audience a BC Wallet specific page might be best.

**Comment by jleach** [comment]
Issue from 2023. Overly stale. Closing.
